### ISSUE TITLE
master_app's schema.ex file does not automatically contain merged mappings/translations

### ISSUE THREAD

**Issue by seantanly** [bitwalker/exrm-umbrella-test#4]
I looked at the master_app and the `apps/master_app/config/config.exs` already contains the settings for app_one and app_two. I assume this is manually added instead of auto generated by exrm, as there isn't any indication that stated master_app is generated by exrm.

Removing the two lines in master_app/config/config.exs, 

```
config :app_one, port: 8090
config :app_two, port: 8091
```

makes the master_app unable to boot both app_one and app_two, because their respective port configurations becomes unable. Inspecting the generated files master_app.schema.exs and master_app.conf show that they are empty.

It seems that exrm's integration with conform isn't merging in the configurations from the app_one and app_two apps as suggested in the README.md.

**Comment by bitwalker** [comment]
Pushed an updated version which uses the new 1.0.0-pre version of conform and the v1 branch of exrm. v1 of exrm is basically master, but with a few small changes to accomodate the new version of conform. 1.0.0-pre of conform is already on hex, and 1.0.0-pre of exrm will be coming soon as well.

**Comment by seantanly** [comment]
Just tried out the updated version and here's some observations.

1. [Need clarification] I believe master_app/config/config.exs is supposed to hold configurations that is meant to override the individual apps default configuration values. Thus, app_one and app_two should be given working defaults instead of nil for port. And master_app can override them to different values.

2. With this in mind, I removed the configs in master_app and restored the defaults in app_one and app_two for testing. Without running conform, executing the release based on master_app, doesn't pick up the port configs in app_one, app_two.

3. [Need fix] Running `conform.new` crashes when master_app/config/config.exs doesn't contain any configuration. Adding a single config allows `conform.new` to execute successfully.
```
$ mix conform.new
==> ranch (compile)
==> cowlib (compile)
==> cowboy (compile)
==> The schema for your project has been placed in config/app_one.schema.exs
==> The schema for your project has been placed in config/app_two.schema.exs
** (ArgumentError) argument error
    :erlang.byte_size(["[", "extends: ", "[]", ",", "\n ", "import: ", "[]", ",", "\n ", "mappings: ", "[]", ",", "\n ", "transforms: ", "[]", ",", "\n ", "validators: ", "[]", "]"])
    lib/conform/schema.ex:289: Conform.Schema.stringify/2
    lib/conform/schema.ex:268: Conform.Schema.write_quoted/2
    lib/mix/tasks/conform.new.ex:46: Mix.Tasks.Conform.New.do_run/2
    (mix) lib/mix/project.ex:196: Mix.Project.in_project/4
    (elixir) lib/file.ex:1137: File.cd!/2
    lib/mix/tasks/conform.new.ex:20: anonymous fn/3 in Mix.Tasks.Conform.New.run/1
    (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
```  

4. [Not working as expected] After executing conform.configure, I checked the master_app.schema.exs, it's not yet picking up the port configs from app_one and app_two automatically. Sure enough, executing the master_app results in a crash from app_one not having a valid port.

**Comment by seantanly** [comment]
Putting this up as a new issue https://github.com/bitwalker/exrm-umbrella-test/issues/5 instead of behind a closed one.
